export const floatingStyle = `
:host{all:initial;position:fixed;z-index:2147483000;display:block;font-family:Inter,"Segoe UI","Microsoft YaHei",sans-serif;color:#272631;font-size:13px;color-scheme:light;--accent:#7054e8;--muted:#92909d}:host([hidden]){display:none!important}*{box-sizing:border-box}button{font:inherit;cursor:pointer}button:focus-visible{outline:2px solid #bba8ff;outline-offset:-2px}[hidden]{display:none!important}svg{display:block;width:20px;height:20px}
#launcher{width:36px;height:36px;padding:8px;border:1px solid #e8e5f0;border-radius:12px;background:#fff;color:var(--accent);box-shadow:0 3px 14px #25203512;display:grid;place-items:center;touch-action:none;transition:box-shadow .15s,background .15s}#launcher:hover{background:#faf8ff;box-shadow:0 4px 18px #25203520}
#panel{width:300px;max-width:calc(100vw - 24px);max-height:calc(100vh - 24px);display:flex;flex-direction:column;border:1px solid #eae7f0;border-radius:16px;background:#fff;box-shadow:0 12px 40px #27213f14,0 2px 8px #27213f08;overflow:hidden}
#drag-handle{height:44px;flex-shrink:0;padding:0 16px;display:flex;align-items:center;justify-content:space-between;cursor:grab;touch-action:none;user-select:none}#drag-handle:active{cursor:grabbing}.brand{display:flex;align-items:center;gap:7px;color:#898391;font-size:11px;font-weight:500;letter-spacing:.15px}.brand svg{width:15px;height:15px;color:var(--accent)}#minimize{border:0;background:transparent;border-radius:6px;padding:5px;color:#aaa6b3;line-height:1}#minimize:hover{color:#57515f;background:#f5f3f8}#minimize svg{width:16px;height:16px}
.summary{padding:0 18px 12px;flex-shrink:0}#title{margin:0 0 10px;color:#282530;font-size:14px;font-weight:600;line-height:1.65;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.meta{display:flex;align-items:center;justify-content:space-between;font-size:10px;line-height:1.5;color:var(--muted)}#count{font-variant-numeric:tabular-nums;color:#aaa4b2}
.outline{min-height:0;max-height:360px;overflow-y:auto;overscroll-behavior:contain;padding:0 8px 10px;scrollbar-width:thin;scrollbar-color:#e5e0ed transparent}#questions{margin:0;padding:0;list-style:none}#questions li{margin:2px 0}#questions button{width:100%;display:flex;align-items:flex-start;gap:10px;padding:11px 10px;border:0;border-radius:9px;background:transparent;color:#6d6778;text-align:left;line-height:1.7;transition:background .15s,color .15s}#questions button:hover{background:#f7f5fa;color:#39323f}#questions button[aria-current="location"]{background:#f2edff;color:#6245cf}.number{flex:0 0 19px;padding-top:1px;color:#b3acbe;font-size:10px;line-height:1.9;font-variant-numeric:tabular-nums}button[aria-current="location"] .number{color:#a38ae8}.question-text{font-size:12px;overflow-wrap:anywhere;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}#empty{margin:8px 10px 14px;font-size:11px;line-height:1.8;color:var(--muted)}
.downloads{flex-shrink:0;display:flex;align-items:center;gap:8px;flex-wrap:wrap;padding:12px 18px;border-top:1px solid #efecf3}#download-format{width:104px;padding:7px 8px;border:1px solid #eae5f2;border-radius:7px;font:inherit;font-size:11px;color:#7e738e;background:#fff}#download{flex:1;padding:8px 14px;border:0;border-radius:8px;background:var(--accent);color:#fff;font-size:11px;font-weight:500}#download:hover{background:#6245d7}#download:disabled,#read-outline:disabled{opacity:.55;cursor:default}.download-status{width:100%;display:flex;align-items:flex-start;gap:8px;justify-content:space-between;line-height:1.7;font-size:10px;color:var(--muted)}#download-status{overflow-wrap:anywhere}#download-status.error{color:#be4d50}#download-cancel,#read-outline{border:0;padding:0;background:transparent;color:var(--accent);font-size:10px;line-height:1.7;white-space:nowrap}#empty p{margin:0 0 7px}
@media(prefers-reduced-motion:reduce){*{transition:none!important}}
`;
